### ISSUE TITLE
如何很快生成大量图形

### ISSUE THREAD

**Issue by wanghaisheng** [leaferjs/LeaferJS#4]
》绚丽多彩的 HTML5 Canvas 2D 图形渲染引擎， 可结合 AI 绘图、生成界面。能让你拥有瞬间创建 100 万个图形的超强能力，免费开源、易学易用、场景丰富。

有没有文档可以参考

**Comment by leaferjs** [comment]
创建100万个矩形：https://www.leaferjs.com/ui/guide/performance.html
